### ISSUE TITLE
[BUG] Auto-sync workflow fails due to missing Git user identity

### ISSUE THREAD

**Issue by adrian-d-hidalgo** [adrian-d-hidalgo/nestjs-mcp-server#44]
## Bug Description

The `.github/workflows/sync-main-to-develop.yml` workflow fails when attempting to create a commit for the automatic sync PR from `main` to `develop`. The error is:

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@...>) not allowed
Error: Process completed with exit code 128.
```

## Steps to Reproduce
1. Merge a `hotfix/*` or `release/*` branch into `main`.
2. The auto-sync workflow triggers and attempts to create a PR to `develop`.
3. The workflow fails at the commit step due to missing Git user identity.

## Expected Behavior
The workflow should configure a valid Git user identity before making commits, so the sync PR is created successfully.

## Suggested Fix
Add the following step before the commit in the workflow:

```yaml
- name: Set up Git user
  run: |
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
    git config --global user.name "github-actions[bot]"
```

This will ensure the commit can be created and pushed without errors.

## Additional Context
See [GitHub Actions docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#github-actions-default-git-configuration) for more details on default Git configuration in runners.

---

_This issue was generated by the AI assistant in response to a workflow failure._
